### ISSUE TITLE
SID是有變動的

### ISSUE THREAD

**Issue by Kudryavka03** [ThanatosDi/sonet-redive#10]
抓包的時候除了第一次的SID是一樣的，其餘的都是變動的

**Comment by Kudryavka03** [comment]
目前瞭解到是md5(sid+一串字符)但我並不知道那串字符是什麽

**Comment by maizuru** [comment]
跟闇詩一樣的話
SID 一開始是viewer_id+udid合拼後的md5
登入之後會變成md5(sid+一串字符)
sid 不會變，字符是UNIX時間，單位為秒

sid如何生成我還未驗證，不過應該是登入時伺服器派的

**Comment by KiruyaMomochi** [comment]
You might want to have a look at how CGSS (IdolM@ster Cinderella Girls) works,
since both of these two games are using `Cute` (made by Cygames) to communicate with the server.

Refer to <https://subdiox.github.io/deresute/> for details.

However, the communication protocol may change in a new version.
For a must-correct answer, reverse engineering, such as decompiling, maybe needed.
Also, please note the risk of reversing.
